name: Test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit and Push
        run: |
          git config user.name "workflow"
          git config user.email "workflow@github.com"
          git pull
          DATE=`date '+%Y%m%d'`
          mkdir $DATE
          cd $DATE
          crul https://radiko.jp/v2/api/noa?station_id=FMT&ft=${DATE}130000&to=${DATE}145500 > ${DATE}.xml
          git add .
          git commit -m "workflow"
          git push origin master
